development:
  adapter: postgresql
  encoding: unicode
  database: obs_development
  pool: 5
  username: obs
  password: 12345
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: obs_test
  pool: 5
  username: obs
  password: 12345
  host: localhost
  port: 5432
